wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/105.mat  -O  IR007_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/118.mat  -O  B007_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/130.mat  -O  OR007@6_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/144.mat  -O  OR007@3_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/156.mat  -O  OR007@12_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/106.mat  -O  IR007_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/119.mat  -O  B007_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/131.mat  -O  OR007@6_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/145.mat  -O  OR007@3_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/158.mat  -O  OR007@12_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/107.mat  -O  IR007_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/120.mat  -O  B007_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/132.mat  -O  OR007@6_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/146.mat  -O  OR007@3_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/159.mat  -O  OR007@12_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/108.mat  -O  IR007_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/121.mat  -O  B007_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/133.mat  -O  OR007@6_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/147.mat  -O  OR007@3_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/160.mat  -O  OR007@12_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/169.mat  -O  IR014_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/185.mat  -O  B014_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/197.mat  -O  OR014@6_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/170.mat  -O  IR014_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/186.mat  -O  B014_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/198.mat  -O  OR014@6_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/171.mat  -O  IR014_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/187.mat  -O  B014_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/199.mat  -O  OR014@6_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/172.mat  -O  IR014_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/188.mat  -O  B014_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/200.mat  -O  OR014@6_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/209.mat  -O  IR021_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/222.mat  -O  B021_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/234.mat  -O  OR021@6_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/246.mat  -O  OR021@3_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/258.mat  -O  OR021@12_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/210.mat  -O  IR021_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/223.mat  -O  B021_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/235.mat  -O  OR021@6_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/247.mat  -O  OR021@3_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/259.mat  -O  OR021@12_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/211.mat  -O  IR021_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/224.mat  -O  B021_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/236.mat  -O  OR021@6_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/248.mat  -O  OR021@3_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/260.mat  -O  OR021@12_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/212.mat  -O  IR021_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/225.mat  -O  B021_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/237.mat  -O  OR021@6_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/249.mat  -O  OR021@3_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/261.mat  -O  OR021@12_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3001.mat -O  IR028_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3005.mat -O  B028_0  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3002.mat -O  IR028_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3006.mat -O  B028_1  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3003.mat -O  IR028_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3007.mat -O  B028_2  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3004.mat -O  IR028_3  
wget http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/3008.mat -O  B028_3  
